# atomproperties.py
"""
    atomproperties.py docstring.....

"""

from numpy import random as rand

__author__ = "Joseph J. Radler"

class Atom(object):
    """Contains atomic specifications and methods for calculating the total
    energy expectation value of the molecule.

    NOTE:  For this simple prototype, only hydrogen atoms in H2 molecules are
           considered. Parameters are hard-coded in at instantiation for now...

    Attributes:
        element                     (string) Element name
        tag                         (int) Tag more than one of the same
                                        element with distinct number
        name                        (string) contcatenated element + tag
        r                           (array float) coordinates of the atom
        z                           (integer) Atomic valence charge (C)
        Lmax
        dq0_guess                   (float) Mullekin charge
                                            fluctuation on Atom
        u                            (float) Hubbard hardness parameter
        e_ks                         (float) 1-electron noninteracting KS energy

    """

    def __init__(self, element, tag, r, u, F0_params, e_ks):
        """Instantiation of Atom class object."""

        ## The electrons can be set to a default from a __dict__ for the
        ##      various elements available in external/slako

        # Declare and Initialize attributes
        self.element = element
        self.tag = tag
        self.name = None                # Generated by set_name
        self.r = r                   # Instantiated in main module for each instance
        self.z = z                      # Hard-coded in for our H2 example.
        self.Lmax = Lmax                # Max angular momentum (s is default)
        self.u = u         # Hubbard parameter for Hydrogen
        self.e_ks = e_ks     # Single atom, single particle KS energy (Hydrogen)
        self.F0_params = F0_params

        print("The F_0 paramters for the atom are: %s" % str(F0_params))

    # Atom Object Class Methods
    def set_name(self, element, tag):
        """Set atom name from input arg strings "element" and "tag"""
        name = element + str(tag)

        return name

    def set_dqguess(self, z):
        """Sets a random initial dq between Z * (0, 1]
        (How is this done in DFTB+?  )"""

        q_guess = abs(z * rand.random())
        dq0_guess = q_guess - z

        return dq0_guess

    # Run upon instance of Atom
    self.name = self.set_name(self.element, self.tag)
    self.dq0_guess = self.set_dqguess(self.z)
