#molecule.py
"""
    atomSpec.py defines classes for:
        Atom objects that contain calculated molecular total energy


        By:         Joseph J. Radler, University of Washington
        Written:    03/20/18
        Appended:   03/21/18

"""

__author__ = "Joseph J. Radler"

import numpy as np
from numpy import random as rand
from numpy import linalg as lg
from numpy import sqrt as sqrt
import scipy
from scipy import special as sp
from helpers import *
#from scc import get_fock1
#from parseinput import parse_atom
#from parseinput import parse_atompair

class Atom(object):
    """Contains atomic specifications and methods for calculating the total
    energy expectation value of the molecule.

    NOTE:  For this simple prototype, only hydrogen atoms in H2 molecules are
           considered. Parameters are hard-coded in at instantiation for now...

    Attributes:
        element                     (string) Element name
        tag                         (int) Tag more than one of the same
                                        element with distinct number
        name                        (string) contcatenated element + tag
        n_elec                      (integer) Total number of valence electrons
        r                           (array float) coordinates of the atom
        z                           (integer) Atomic valence charge (C)
        l_max
        q_guess                     (float) Random number btw [0,Z]
        dq0_guess                   (float) Mullekin charge
                                            fluctuation on Atom
        u                            (float) Hubbard hardness parameter
        e_ks                         (float) 1-electron noninteracting KS energy
    Methods:
        set_dq()
        set_name()
    """

    def __init__(self, element, tag, r, z = 1, l_max = 1) :
        """Instantiation of Atom class object."""

        ## The electrons can be set to a default from a __dict__ for the
        ##      various elements available in external/slako

        # Declare and Initialize attributes
        self.element = None
        self.tag = None
        self.name = None                # Generated by set_name
        self.r = r                   # Instantiated in main module for each instance
        self.z = z                      # Hard-coded in for our H2 example.
        self.n_elec = None                 # Hardcoded for now...
        self.l_max = None                 # Highest occ orbital corr. to s-type
        self.q_guess = None
        self.dq0_guess = None
        self.u = None         # Hubbard parameter for Hydrogen
        self.e_ks = None      # Single atom, single particle KS energy (Hydrogen)


    # Atom Object Class Methods
    def set_name(self):
        """Set atom name from input arg strings "element" and "tag"""
        self.name = self.element + str(self.tag)

        return None

    def set_dqguess(self):
        """Sets a random initial dq between Z * (0, 1]
        (How is this done in DFTB+?  )"""

        self.q_guess = abs(self.z * rand.random())
        self.dq0_guess = self.q_guess - self.z

        return None
    # Class instantiation statements

class Molecule(object):
    """Molecule objects contain information about the Atom objects and
    the interactions between AtomPair objects in the DFTB method to
    initialize the self-consistent charge (SCC) calculation.

    Attributes:
        name
        atom
        atompair
        ntot_elec
        mtot_atoms
        ptot_pairs
        c_vec
        totalfock_i
        fock0_i
        fock1_i
        overlap
    Methods:
        nearest_neighbors()
    """

    def __init__(self, name, atoms_list):
        """Instantiate members of Molecule object"""
        self.name = name    # Generate a formula ``name`` from atom list
        self.ntot_elec = None   # Compute from iterating over all AtomPairs
        self.mtot_atoms = None
        #self.ptot_pairs = None
        self.c_vec = None
        self.totalfock_i = None
        self.fock0_i = None
        self.fock1_i = None
        self.overlap = None

        # Member instantiation statements

        self.ntot_elec = set_ntot_elec(self, atoms_list)
        self.mtot_atoms = len(atoms_list)
        self.overlap = buildoverlap(atoms_list)
        self.fock0_i = buildfock0_i(atoms_list)
        self.fock1_i = buildfock1_i(atoms_list)
        self.totalfock_i = buildtotalfock_i(self.fock0_i, self.fock1_i,\
                self.overlap)
        self.c_vec = build_c_i(atoms_list)


class AtomPair(object):
    """Contains atomic pairwise interaction parameters as member objects.

    Attributes:
        name                (str)
        atom_a              (object)
        atom_b              (object)
        u_a                 (float)
        u_b                 (float)
        r_a                 (array)
        r_b                 (array)
        r_ab                (float)
        pairtype            (int)
        sameatom            (bool)
        pair_bondtypes      (int)
        pair_n_elecs        (int)
        d_ab                (float)
        gamma_ab            (float)
    Methods:
        set_pairname(atom_a, atom_b)      Returns member object.name
        set_n_elecs(atom_a, atom_b)       Returns number of valence electrons
        calc_r(atom_a, atom_b)            Returns internuclear distance R_ab
        pair_type(atom_a, atom_b)         Returns the type of interaction
                                           (e.g. hetero/homonuclear or same atom)
        bond_types()                      Returns bond-type indicator
        set_gamma(pairtype, u_a, u_b, r_ab)
                                          Returns the A-B polarization
                                            interaction parameter gamma_ab
        set_fock0_ab                      Returns the fock0 element for the pair
        set_overlap_ab                    Returns the overlap elem for the pair
        set_fock1_ab                      Returns the fock1 elem for the pair
    """

    def __init__(self, atom_a, atom_b):
        """Instantiate and initialize (currently hardcoded) parameters"""
        # TODO: place most of the methods into a "helper functions" module
        # rather than listing them all here, then use them as calls to
        # set the object values upon instantiation of molecule, not atompairs.
        self.u_a = None
        self.u_b = None
        self.r_a = None
        self.r_b = None
        self.name = None
        self.r_ab = None                # calculate with AtomPair.calc_R
        self.pairtype = None
        self.sameatom = None
        self.pair_bondtypes = None       # Set with an AtomPair method later
        self.pair_n_elecs = None
        self.gamma_ab = None            # Set with set_gamma() method
        self.fock0_ab = None
        self.fock1_ab = None
        self.overlap_ab = None

        def set_pairname(self, atom_a, atom_b):
            """docstring"""
            name = atom_a.name + atom_b.tag
            return name

        def set_n_elecs(self, atom_a, atom_b):
            """docstring"""
            n_elecs = atom_a.n_elecs + atom_b.n_elecs
            return n_elecs

        def calc_r(self, atom_a, atom_b):
            """calculates the bond pair interatomic distance r_ab"""
            r_a = atom_a.r
            r_b = atom_b.r
            r_ab = lg.norm(r_a - r_b)
            return r_ab

        def pair_type(self, atom_a, atom_b):
            """determines type (same atom =0 ,homonuclear = 1, heteronuclear = 2)
            of pairwise interaction."""
            if atom_a.name is not atom_b.name:
                if atom_a.element is not atom_b.element:
                    pairtype = 2
                else:
                    pairtype = 1
            else:
                pairtype = 0

            return pairtype

        def bond_types(self):
            """determines the bond types (sigma = 0, pi = 1, delta = 2) from the
            l_max of each Atom object local copy."""
            # TODO: write appropriate set of conditionals to generalize
            pair_bondtypes = 0
            return pair_bondtypes

        def set_gamma(self, pairtype, u_a, u_b, r_ab):
            """sets the value of self.gamma_ab based on interaction type."""
            if pairtype != 0:
                # Case where  both electrons are NOT on the same atom (atom A)
                d_ab = sqrt((1.56 * (u_a**2) * (u_b**2)) / ((u_a**2) + (u_b**2)))
                gamma_ab = (1 / r_ab) * sp.erf(r_ab * d_ab)

            else:
                # Case where both electrons are on the same atom (atom A).
                gamma_ab = u_a      # gamma_aa = u_a
            return gamma_ab

        def set_fock0_ab(self, atom_a, atom_b):
            """docstring"""
            pass

        def set_fock1_ab(self, atom_a, atom_b):
            """docstring"""
            pass

        def set_overlap_ab(self, atom_a, atom_b):
            """docstring"""
            pass

        # Class instantiation value assignments
        self.u_a = atom_a.u
        self.u_b = atom_b.u
        self.r_a = atom_a.r
        self.r_b = atom_b.r
        self.name = set_pairname(self, atom_a, atom_b)
        self.r_ab = calc_r(self, atom_a.r, atom_b.r)
        self.pairtype = pair_type(self, atom_a, atom_b)

        if atom_a.name is atom_b.name:
            self.sameatom = True
        else:
            self.sameatom = False

        self.pair_bondtypes = bond_types(self)
        self.pair_n_elecs = set_n_elecs(self, atom_a, atom_b)
        self.gamma_ab = set_gamma(self, self.pairtype, self.u_a, self.u_b, self.r_ab)
        self.fock0_ab = set_fock0_ab(self, atom_a, atom_b)
        self.fock1_ab = set_fock1_ab(self, atom_a, atom_b)
        self.overlap_ab = set_overlap_ab(self, atom_a, atom_b)
